### ISSUE TITLE
icon navigator copying wrong import

### ISSUE THREAD

**Issue by jdgaravito** [gibdig/svelte-icons#5]
hi. i started to use your svelte icons pack, but the icon navigator sometimes is copying the  previous icon import i used.

it will be great to have the option see the snippet and not just forcing you  to copy right to the clipboard. Something similar to the official material-icons site has.

Thanks

**Comment by aidensV** [comment]
Same problem when searching for icons

**Comment by joelhickok** [comment]
This happens constantly, and has for weeks.  I just browse them with the Icon Navigator, and then import them by name using code completion in the import.

**Comment by jdgaravito** [comment]
seems the dev forgot about this project and is dead. what can we do to fix it and add more icon packs?

**Comment by joelhickok** [comment]
Somebody could fork it, or re-create it... re-brand it... but I think as Svelte gains momentum the ecosystem and number of libraries is going to take off in the next year.  If I get more time after some work projects get done, I'm happy to get involved... but I have little free time right now.

Or perhaps the person who built it will come alive again.

**Comment by joelhickok** [comment]
FYI, this project is only for Font Awesome, but is a good choice.
[https://cweili.github.io/svelte-fa/](https://cweili.github.io/svelte-fa/)

**Comment by gibdig** [comment]
sorry about the delay on this, I have not looked at the project in a long while and for whatever reason I was not getting notifications, I will push a fix for this soon.

**Comment by gibdig** [comment]
closing with: https://github.com/gibdig/svelte-icons/commit/69bfd6c9fce4349219d73cf68771786b8f7363df & https://github.com/gibdig/svelte-icons/commit/f9ff26ae5e3fc45a429ad0f9e5775335d06dff9e
